Repository abhijeet141/CropForesight-FrontEnd, pull requests merged in 2023-06, with the labels that each got.

#37 responsive home page
  src/components/Home.css
  src/components/nav.css
Labels: gssoc23, level2

#41 Fix: Navbar items alignment
  src/components/Home.js
  src/components/nav.css
Labels: gssoc23, level1

#64 Responsive ContactUs
  src/App.css
  src/components/about.css
  src/components/contact.css
  src/components/contact.js
Labels: level1

#53 About Title Centered + Some Padding Provided
  src/components/about.css
  src/components/about.js
Labels: gssoc23, level1

#74 made the contact page and weather page responsive for mobile devices
  src/components/404.css
  src/components/404.js
  src/components/Weather.css
  src/components/Weather.js
  src/components/contact.css
Labels: gssoc23, level2

#126 Add Preloading Feature
  public/index.html
  public/preloading.css
  src/App.js
  src/components/faq/faq.jsx
Labels: gssoc23, level2

#129 Converted images to WebP
  src/App.css
  src/assets/about.png
  src/assets/about.webp
  src/assets/earth.png
  src/assets/earth.webp
  src/assets/faq.png
  src/assets/faq.webp
  src/assets/image.jpg
  src/assets/image.webp
  src/assets/menu-icon.png
  src/assets/menu-icon.webp
  src/components/404.js
  src/components/Home.js
  src/components/Weather.js
  src/components/about.js
  src/components/contact.js
  src/components/faq/faq.jsx
  src/components/nav.jsx
Labels: gssoc23, level1

#123 Issue #109 is solved.
  src/App.css
  src/App.js
  src/components/Home.css
  src/components/about.css
  src/components/contact.css
Labels: gssoc23, level1

#133 Contact us page css updated
  src/components/contact.css
  src/components/contact.js
Labels: gssoc23, level2

#128 Issue #104 Updated the Meta Tags for Improved SEO on CropForesight Website
  public/index.html
Labels: gssoc23, level1

#137 changes made in card and button of homepage
  src/components/Home.css
  src/components/Home.js
Labels: gssoc23, level2
